// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
int x = 5;
int y = 10;
Console.WriteLine(x + y);
Console.WriteLine(x += y);
Console.WriteLine(x -= y);
Console.WriteLine(x *= y);
int nuray = 5;
double myName = 7.2D;
char myLast = 'A';
bool myBolt = false;
string myTail = "Hi";
int a = 5;
int b = 4;
Console.WriteLine(a/= b);
Console.WriteLine(a %=b);
Console.WriteLine(a &= b);
Console.WriteLine(a |= b);
Console.WriteLine(a ^= b);
Console.WriteLine(a>>=b);
Console.WriteLine(a<<=b);
Console.WriteLine(a==b);
Console.WriteLine(a!=b);
Console.WriteLine(a>b);
Console.WriteLine(a<b);
Console.WriteLine(a>=b);
Console.WriteLine(a<=b);
